baseURL = 'https://power44.me/'
languageCode = 'en-us'
title = 'Julian Power'
theme = "re-terminal"
paginate = 5
sectionPagesMenu = "main"

[params]
  centerTheme = false
  themeColor= "custom"
  fullWidthTheme = true
[languages.en.params.logo]
  logoText = "Julian Power"
  logoHomeLink = "/"